### ISSUE TITLE
出问题了，求大佬带带

### ISSUE THREAD

**Issue by LllllFancy** [Coelophylla/jksb-sysu#6]
[INFO] 2022-10-18 21:21:15,325 点击下一步
[54](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:55)
[INFO] 2022-10-18 21:21:15,606 提交健康申报
[55](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:56)
[INFO] 2022-10-18 21:21:20,565 访问健康申报页面
[56](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:57)
[INFO] 2022-10-18 21:21:22,999 打开健康申报成功
[57](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:58)
[INFO] 2022-10-18 21:21:22,999 点击下一步
[58](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:59)
[INFO] 2022-10-18 21:21:23,282 提交健康申报
[59](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:60)
Traceback (most recent call last):
[60](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:61)
  File "D:\a\jksb-sysu\jksb-sysu\jksb_sysu.py", line 115, in <module>
[61](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:62)
    jksb(driver)
[62](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:63)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\retrying.py", line 49, in wrapped_f
[63](https://github.com/LllllFancy/jksb-sysu/actions/runs/3273766264/jobs/5386403575#step:4:64)
    return Retrying(*dargs, **dkw).call(f, *args, **kw)

**Comment by LllllFancy** [comment]
卡在申报循环了

**Comment by Aoi-cn** [comment]
学校加了遮罩，fork我的就行
```
[INFO] 2022-[10](https://github.com/Aoi-cn/jksb-sysu/actions/runs/3269516527/jobs/5377101118#step:4:11)-18 07:54:48,979 初始化selenium driver完成
[INFO] 2022-10-18 07:54:49,183 初始化ddddocr完成
[INFO] 2022-10-18 07:54:49,183 访问登录页面
[INFO] 2022-10-18 07:54:57,528 读取用户名密码
[INFO] 2022-10-18 07:54:57,528 输入用户名密码
[INFO] 2022-10-18 07:54:59,782 下载验证码图片成功
[INFO] 2022-10-18 07:54:59,806 验证码识别成功：tpsm
[INFO] 2022-10-18 07:54:59,806 输入验证码
[INFO] 2022-10-18 07:54:59,821 点击登录按钮
[INFO] 2022-10-18 07:55:04,395 登录成功
[INFO] 2022-10-18 07:55:04,395 访问健康申报页面
[INFO] 2022-10-18 07:55:[16](https://github.com/Aoi-cn/jksb-sysu/actions/runs/3269516527/jobs/5377101118#step:4:17),[18](https://github.com/Aoi-cn/jksb-sysu/actions/runs/3269516527/jobs/5377101118#step:4:19)3 打开健康申报成功
[INFO] [20](https://github.com/Aoi-cn/jksb-sysu/actions/runs/3269516527/jobs/5377101118#step:4:21)22-10-18 07:55:16,183 点击下一步
[INFO] 2022-10-18 07:55:16,473 出现终止按钮，先睡一会
[INFO] 2022-10-18 07:55:[21](https://github.com/Aoi-cn/jksb-sysu/actions/runs/3269516527/jobs/5377101118#step:4:22),474 醒了，看看下一步能不能点了
[INFO] 20[22](https://github.com/Aoi-cn/jksb-sysu/actions/runs/3269516527/jobs/5377101118#step:4:23)-10-18 07:55:21,489 可以咯，提交健康申报
[INFO] 2022-10-18 07:55:22,791 完成健康申报
```

**Comment by LllllFancy** [comment]
谢谢大佬！！！

**Comment by Coelophylla** [comment]
已经merge @Aoi-cn提交的修改。
